[package]
name = "curunir"
version = "0.1.0"
authors = ["Kyle Stang <kylestang.ks@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/kylestang/battlesnake-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "1.1.1"
serde = "1.0.116"
image = "0.23.10"
